version: '3.8'

services:
  spring-jwt:
    image: ghcr.io/softwarity/spring-jwt
    ports:
      - 9292:8080
    secrets:
      - jwt_public_key
    environment:
      JWT_PUBLIC_KEY_FILE: /run/secrets/jwt_public_key
      JWT_ALGORITHM: RS256
    networks:
      - dnet

secrets:
  jwt_public_key:
    external: true

networks:
  dnet: