server:
  port: ${PORT:8080}
spring:
  profiles:
    active: default
  config:
    import:
      - "optional:file:env.properties"
management:
  endpoints:
    web:
      exposure:
        include: health
jwt:
  pem-path: "${JWT_PUBLIC_KEY_FILE:}"
  algorithm: "${JWT_ALGORITHM:}"
