server:
  port: ${PORT:8080}
spring:
  config:
    import:
      - "optional:file:env.properties"
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health
jwt:
  pem-path: "${JWT_PUBLIC_KEY_FILE:}"
  algorithm: "${JWT_ALGORITHM:}"
