name: Build
run-name: ${{ github.actor }} run build on ${{ github.repository }}
on:
  push:
    branches:
      - '*'
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
jobs:
  build-spring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: liberica
      - run: mvn -Dmaven.test.skip=true clean package
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          build-args: GIT_TAG_REV=$GITHUB_SHA
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:latest
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: |
          ssh -o StrictHostKeyChecking=no github_action@demo.hhdev.fr "docker login -u hhfrancois -p ${{ secrets.TOKEN_READ_PACKAGE }} https://ghcr.io"
          ssh -o StrictHostKeyChecking=no github_action@demo.hhdev.fr "docker service update --image ghcr.io/${{ github.repository }}@\$(docker pull ghcr.io/${{ github.repository }}:latest | grep sha | sed 's/Digest: //') --label-add updated_at=$(date -u -Iseconds) panoptes_spring-jwt"
